<?php 
	ini_set('memory_limit', '-1');
	//ini_set('MAX_EXECUTION_TIME', '-1');
	ini_set('max_execution_time', 300);
?>
<style>
	.simpleTable{
		text-align:left;
	}
	
	.simpleTable th, .simpleTable td{
		line-height:normal;
		text-align:left;
		font-weight:normal;
	}
	
	#subjectNameList{
		line-height:20px;
	}
	
	
	@media print{
		pageBreak{
			page-break-after:always;
			page-break-inside:avoid;
		}
	}
</style>
<html>
	<head>
		<title> Dokani: It Lab Solutions </title>
		<link rel="stylesheet" href="<?php echo base_url(); ?>style/transcript_style.css" type="text/css"/> 
		<!--script src="<?php echo base_url();?>assets/js/jquery.min.js"></script-->
	</head>
	
	<body>
		<div id="main">
			<div id="controller">
				<htmlpageheader name="myheader">
					<div id="header">
						<img style="width:10%;" class="schoolLogoHeaderSmall" src="<?php echo base_url();?>images/top_logo.png"/>
						<h1 style="font-size:18px; line-height:normal;width:90%;" class="schoolNameHeaderSmall"> 
							<?php echo $this->tank_auth->get_shopname().' ( '. $this->tank_auth->get_shopaddress().' ) '; ?>
						</h1>
						<h3 class="pageTitleSmall" style="margin:10px 0px 5px 0px;"> Sale Report </h3>
					</div>
				</htmlpageheader>
				<htmlpagefooter name="myfooter">
					<div id="printFooter">
						<div class="part70P"> 
							<div class="developPart">
								<img class="companyLogo" src="<?php echo base_url();?>images/itlablogo.png" alt="IT Lab Solutions Ltd."/>
								
								<p> 
									Generated By : <b>Dokani</b> 
									<br/>
									Developed By : <b>IT Lab Solutions Ltd.</b> +8801842485222, www.itlabsolutions.com
								</p> 
							</div>
						</div>
						
						
						<div class="part30P">
							<div class="orgNameBottom textAlginRight">
								<p> <b>&copy; Copyright </b> <br/>  <?php echo $this->tank_auth->get_shopname();?>  </p>
								<p> <?php echo $this->tank_auth->get_shopaddress();?> </p>
							</div>
						</div>
					</div>
				</htmlpagefooter>
				<sethtmlpageheader name="myheader" value="on" show-this-page="1" />
				<sethtmlpagefooter name="myfooter" value="on" />
				<?php if($this->uri->segment(8)=='invoice'){?>
				<div class="row">
					<table class="simpleTable" style="margin-top:15px;">
						<thead>
							<tr class="tableRowBG">
								<th colspan="3" style="text-align:center;">No</th>
								<th colspan="3" style="text-align:center;">Date</th>
								<th colspan="3" style="text-align:left;">Customer</th>
								<th colspan="3" style="text-align:center;">Invoice</th>
								<th colspan="6" style="text-align:right;">Sale</th>
								<th colspan="6" style="text-align:right;">Discount</th>
								<th colspan="6" style="text-align:right;">Sale return</th>
								<th colspan="6" style="text-align:right;">Delivery</th>
								<th colspan="6" style="text-align:right;">Grand</th>
								<th colspan="6" style="text-align:right;">Paid</th>
								<th colspan="6" style="text-align:right;">Due</th>
								<th colspan="6" style="text-align:center;">Payment</th>
								<th colspan="6" style="text-align:center;">Seller</th>
							</tr>
						</thead>	
						<tbody>	
						<?php
						$index = 1;
						$total_buy=0;
						$total_price=0;
						$sale_return_amount=0;
						$discount_amount=0;
						$delivery_charge=0;
						$total_quantity=0;
						$total_paid=0;
						$grand_sale=0;
						$total_receivable=0;
						foreach($download_data_sale -> result() as $field):
						?>
							<tr>
								<th colspan="3" style="text-align:center;"> <?php echo $index; ?>  </th>
								<th colspan="3" style="text-align:center;"> <?php echo $field->invoice_doc; ?>  </th>
								<th colspan="3" style="text-align:left;"> <?php echo $field->customer_name; ?>  </th>
								<th colspan="3" style="text-align:center;"> <?php echo $field->invoice_id; ?>  </th>
								<th colspan="6" style="text-align:right;"> <?php echo sprintf('%0.2f',$field ->total_price); ?> </th>
								<th colspan="6" style="text-align:right;"> <?php echo sprintf('%0.2f',$field ->discount_amount); ?> </th>
								<th colspan="6" style="text-align:right;"> <?php echo sprintf('%0.2f',$field ->sale_return_amount); ?> </th>
								<th colspan="6" style="text-align:right;"> <?php echo sprintf('%0.2f',$field ->delivery_charge); ?> </th>
								<th colspan="6" style="text-align:right;"> <?php echo sprintf('%0.2f',$field ->grand_total); ?> </th>
								<th colspan="6" style="text-align:right;"> <?php echo sprintf('%0.2f',$field ->total_paid); ?> </th>
								<th colspan="6" style="text-align:right;"> 
								<?php
									/* if($field ->sale_return_amount !='' && $field ->sale_return_amount!=$field ->grand_total)
									{
										$total_due  = $field ->grand_total + $field ->sale_return_amount - $field ->total_paid;
									}
									else if($field ->sale_return_amount==$field ->grand_total)
									{
										$total_due  = $field ->grand_total - $field ->total_paid;
									}
									else
									{ */
										$total_due  = $field ->grand_total - $field ->total_paid;
									/* } */							
									if($field ->grand_total=='0' && $field ->total_paid=='0')
									{
										$total_due  = '0.00';
									}
									else if($total_due < 0)
									{
										$total_due  = '0.00';
									}
									echo sprintf('%0.2f',$total_due);
									//echo sprintf('%0.2f',$field ->grand_total - $field ->total_paid); 
								?> 
								</th>
								<th colspan="6" style="text-align:center;"> <?php echo $field->payment_mode; ?> </th>
								<td colspan="6" style="text-align:center;"> <?php echo $field ->username; ?> </td>
								
								<?php 
								
									$total_price += $field -> total_price;
									$sale_return_amount += $field -> sale_return_amount;
									$delivery_charge += $field -> delivery_charge;
									$total_paid += $field -> total_paid;
									$discount_amount += $field -> discount_amount;
									$grand_sale += $field -> grand_total;
									$total_receivable += $total_due;
								?>
							</tr>
						<?php
							$index++;
							endforeach;
							
						?>
						</tbody>
					</table>
				</div>
				
				<div class="row">
					<h3 class="pageTitleSmall" style="margin:20px 0 5px 0;"> Summary </h3>
					<table class="simpleTable" style="margin-top:30px;">
						<thead>
							<tr class="tableRowBG">
								<th colspan="3" style="text-align:center;">Total Sale</th>
								<th colspan="3" style="text-align:center;">Discount</th>
								<th colspan="3" style="text-align:center;">Sale Return</th>
								<th colspan="3" style="text-align:center;">Delivery</th>
								<th colspan="3" style="text-align:center;">Grand</th>
								<th colspan="3" style="text-align:center;">Total Received</th>
								<th colspan="3" style="text-align:center;">Total Due</th>
							</tr>
						</thead>	
						<tbody>	
							<tr>
								<th colspan="3" style="text-align:center;"> <?php echo sprintf('%0.2f',$total_price); ?>  </th>
								<th colspan="3" style="text-align:center;"> <?php echo sprintf('%0.2f',$discount_amount); ?>  </th>
								<th colspan="3" style="text-align:center;"> <?php echo sprintf('%0.2f',$sale_return_amount); ?>  </th>
								<th colspan="3" style="text-align:center;"> <?php echo sprintf('%0.2f',$delivery_charge); ?>  </th>
								<th colspan="3" style="text-align:center;"> <?php echo sprintf('%0.2f',$grand_sale); ?>  </th>
								<th colspan="3" style="text-align:center;"> <?php echo sprintf('%0.2f',$total_paid); ?>  </th>
								<th colspan="3" style="text-align:center;"> <?php echo sprintf('%0.2f',$total_receivable ); ?>  </th>
							</tr>
						</tbody>
					</table>
				</div>
				<?php } else if ($this->uri->segment(8)=='product'){?>
				<div class="row">
					<table class="simpleTable" style="margin-top:30px;">
						<thead>
							<tr class="tableRowBG">
								<th colspan="3" style="text-align:center;">No</th>
								<th colspan="6" style="text-align:center;">Product</th>
								<th colspan="4" style="text-align:center;">Company</th>
								<th colspan="6" style="text-align:center;">Category</th>
								<th colspan="6" style="text-align:center;">Quantity</th>
								<th colspan="6" style="text-align:center;">Customer</th>
								<th colspan="6" style="text-align:center;">BP</th>
								<th colspan="6" style="text-align:center;">SP</th>
								<th colspan="6" style="text-align:center;">Seller</th>
							</tr>
						</thead>	
						<tbody>	
						<?php
						$index = 1;
						$total_buy=0;
						$total_sale=0;
						$total_quantity=0;
						$total_paid=0;
						$grand_sale=0;
						foreach($download_data_sale -> result() as $field):
						?>
							<tr>
								<th colspan="3" style="text-align:center;"> <?php echo $index; ?>  </th>
								<th colspan="6" style="text-align:left;"> <?php echo $field->product_name; ?>  </th>
								<th colspan="4" style="text-align:left;"> <?php echo $field->company_name; ?> </th>
								<th colspan="6" style="text-align:left;"> <?php echo $field->catagory_name; ?> </th>
								<th colspan="6" style="text-align:center;"> <?php echo $field -> number_of_quantity; ?> </th>
								<th colspan="6" style="text-align:left;"> <?php echo $field -> customer_name; ?> </th>
								<td colspan="6" style="text-align:right;"> <?php $u_bp = $field ->unit_buy_price * $field ->number_of_quantity; echo sprintf('%0.2f',$u_bp); ?> </td>
								<td colspan="6" style="text-align:right;"> <?php $u_sp= $field ->unit_sale_price * $field ->number_of_quantity; echo sprintf('%0.2f',$u_sp); ?> </td>
								<td colspan="6" style="text-align:center;"> <?php echo $field ->username; ?> </td>
								
								<?php $total_quantity += $field -> number_of_quantity;?>
								<?php $total_buy += $field ->unit_buy_price * $field ->number_of_quantity;?>
								<?php $total_sale += $field ->unit_sale_price * $field ->number_of_quantity;?>
							</tr>
						<?php
							$index++;
							endforeach;
							
						?>
						</tbody>
					</table>
				</div>
				
				<div class="row">
					<h3 class="pageTitleSmall" style="margin:20px 0 5px 0;"> Summary </h3>
					<table class="simpleTable" style="margin-top:30px;">
						<thead>
							<tr class="tableRowBG">
								<th colspan="3" style="text-align:center;">Total Quantity</th>
								<th colspan="3" style=";text-align:center;">Total Buy</th>
								<th colspan="3" style="text-align:center;">Total Sale</th>
								<th colspan="3" style="text-align:center;">Total Profit</th>
							</tr>
						</thead>	
						<tbody>	
							<tr>
								<th colspan="3" style="text-align:center;"> <?php echo $total_quantity; ?>  </th>
								<th colspan="3" style="text-align:right;"> <?php echo sprintf('%0.2f',$total_buy); ?>  </th>
								<th colspan="3" style="text-align:right;"> <?php echo sprintf('%0.2f',$total_sale); ?>  </th>
								<th colspan="3" style="text-align:right;"> <?php echo sprintf('%0.2f',$total_sale-$total_buy); ?>  </th>
							</tr>
						</tbody>
					</table>
				</div>
				<?php } else if ($this->uri->segment(8)=='invoice_product'){?>
				<div class="row">
					<table class="simpleTable" style="margin-top:30px;">
						<thead>
							<tr class="tableRowBG">
								<th colspan="3" style="text-align:center;">No</th>
								<th colspan="3" style="text-align:center;">Date</th>
								<th colspan="3" style="text-align:center;">Invoice</th>
								<th colspan="6" style="text-align:center;">Company</th>
								<th colspan="6" style="text-align:center;">Category</th>
								<th colspan="6" style="text-align:center;">Product</th>
								<th colspan="6" style="text-align:center;">Quantity</th>
								<th colspan="6" style="text-align:center;">Customer</th>
								<th colspan="6" style="text-align:center;">BP</th>
								<th colspan="6" style="text-align:center;">SP</th>
								<th colspan="6" style="text-align:center;">Seller</th>
							</tr>
						</thead>	
						<tbody>	
						<?php
						$index = 1;
						$total_buy=0;
						$total_sale=0;
						$total_quantity=0;
						$total_paid=0;
						$grand_sale=0;
						foreach($download_data_sale -> result() as $field):
						?>
							<tr>
								<th colspan="3" style="text-align:center;"> <?php echo $index; ?>  </th>
								<th colspan="3" style="text-align:center;"> <?php echo $field->invoice_doc; ?>  </th>
								<th colspan="3" style="text-align:center;"> <?php echo $field->invoice_id; ?>  </th>
								<th colspan="6" style="text-align:center;"> <?php echo $field->company_name; ?> </th>
								<th colspan="6" style="text-align:center;"> <?php echo $field->catagory_name; ?> </th>
								<th colspan="6" style="text-align:center;"> <?php echo $field->product_name; ?> </th>
								<th colspan="6" style="text-align:center;"> <?php echo $field -> sale_quantity; ?> </th>
								<th colspan="6" style="text-align:center;"> <?php echo $field -> customer_name; ?> </th>
								<td colspan="6" style="text-align:right;"> <?php $u_bp = $field ->unit_buy_price * $field -> sale_quantity; echo sprintf('%0.2f',$u_bp); ?> </td>
								<td colspan="6" style="text-align:right;"> <?php $u_sp= $field ->unit_sale_price * $field -> sale_quantity; echo sprintf('%0.2f',$u_sp); ?> </td>
								<td colspan="6" style="text-align:center;"> <?php echo $field ->username; ?> </td>
								
								<?php $total_quantity += $field -> sale_quantity;?>
								<?php $total_buy += $field ->unit_buy_price * $field ->sale_quantity;?>
								<?php $total_sale += $field ->unit_sale_price * $field ->sale_quantity;?>
							</tr>
						<?php
							$index++;
							endforeach;
							
						?>
						</tbody>
					</table>
				</div>
				
				<div class="row">
					<h3 class="pageTitleSmall" style="margin:20px 0 5px 0;"> Summary </h3>
					<table class="simpleTable" style="margin-top:30px;">
						<thead>
							<tr class="tableRowBG">
								<th colspan="3" style="text-align:center;">Total Quantity</th>
								<th colspan="3" style="text-align:center;">Total Buy</th>
								<th colspan="3" style="text-align:center;">Total Sale</th>
							</tr>
						</thead>	
						<tbody>	
							<tr>
								<th colspan="3" style="text-align:center;"> <?php echo $total_quantity; ?>  </th>
								<th colspan="3" style="text-align:right;"> <?php echo  sprintf('%0.2f',$total_buy); ?>  </th>
								<th colspan="3" style="text-align:right;"> <?php echo sprintf('%0.2f',$total_sale); ?>  </th>
							</tr>
						</tbody>
					</table>
				</div>
				<?php } else {?>
				<div class="row">
					<table class="simpleTable" style="margin-top:30px;">
						<thead>
							<tr class="tableRowBG">
								<th colspan="3" style="text-align:center;">No</th>
								<th colspan="3" style="text-align:center;">Date</th>
								<th colspan="3" style="text-align:center;">Invoice</th>
								<th colspan="6" style="text-align:center;">Company</th>
								<th colspan="6" style="text-align:center;">Category</th>
								<th colspan="6" style="text-align:center;">Product</th>
								<th colspan="6" style="text-align:center;">Quantity</th>
								<th colspan="6" style="text-align:center;">Customer</th>
								<th colspan="6" style="text-align:center;">BP</th>
								<th colspan="6" style="text-align:center;">SP</th>
								<th colspan="6" style="text-align:center;">Seller</th>
							</tr>
						</thead>	
						<tbody>	
						<?php
						$index = 1;
						$total_buy=0;
						$total_sale=0;
						$total_quantity=0;
						$total_paid=0;
						$grand_sale=0;
						foreach($download_data_sale -> result() as $field):
						?>
							<tr>
								<th colspan="3" style="text-align:center;"> <?php echo $index; ?>  </th>
								<th colspan="3" style="text-align:center;"> <?php echo $field->invoice_doc; ?>  </th>
								<th colspan="3" style="text-align:center;"> <?php echo $field->invoice_id; ?>  </th>
								<th colspan="6" style="text-align:center;"> <?php echo $field->company_name; ?> </th>
								<th colspan="6" style="text-align:center;"> <?php echo $field->catagory_name; ?> </th>
								<th colspan="6" style="text-align:center;"> <?php echo $field->product_name; ?> </th>
								<th colspan="6" style="text-align:center;"> <?php echo $field -> number_of_quantity; ?> </th>
								<th colspan="6" style="text-align:center;"> <?php echo $field -> customer_name; ?> </th>
								<td colspan="6" style="text-align:right;"> <?php $u_bp = $field ->unit_buy_price * $field -> number_of_quantity; echo sprintf('%0.2f',$u_bp); ?> </td>
								<td colspan="6" style="text-align:right;"> <?php $u_sp= $field ->unit_sale_price * $field -> number_of_quantity; echo sprintf('%0.2f',$u_sp); ?> </td>
								<td colspan="6" style="text-align:center;"> <?php echo $field ->username; ?> </td>
								
								<?php $total_quantity += $field -> number_of_quantity;?>
								<?php $total_buy += $field ->unit_buy_price * $field ->number_of_quantity;?>
								<?php $total_sale += $field ->unit_sale_price * $field ->number_of_quantity;?>
							</tr>
						<?php
							$index++;
							endforeach;
							
						?>
						</tbody>
					</table>
				</div>
				
				<div class="row">
					<h3 class="pageTitleSmall" style="margin:20px 0 5px 0;"> Summary </h3>
					<table class="simpleTable" style="margin-top:30px;">
						<thead>
							<tr class="tableRowBG">
								<th colspan="3" style="color:white;text-align:center;">Total Quantity</th>
								<th colspan="3" style="color:white;text-align:center;">Total Buy</th>
								<th colspan="3" style="color:white;text-align:center;">Total Sale</th>
							</tr>
						</thead>	
						<tbody>	
							<tr>
								<th colspan="3" style="text-align:center;"> <?php echo $total_quantity; ?>  </th>
								<th colspan="3" style="text-align:right;"> <?php echo  sprintf('%0.2f',$total_buy); ?>  </th>
								<th colspan="3" style="text-align:right;"> <?php echo sprintf('%0.2f',$total_sale); ?>  </th>
							</tr>
						</tbody>
					</table>
				</div>
				<?php } ?>
			</div> <!---------- END OF DIV CONTROLLER ---------->
		</div>	<!--------- END OF DIV MAIN --------->
	</body>
</html>
