<?php 
	ini_set('memory_limit', '-1');
	//ini_set('MAX_EXECUTION_TIME', '-1');
	ini_set('max_execution_time', 300);
?>
<style>
	.simpleTable{
		text-align:left;
	}
	
	.simpleTable th, .simpleTable td{
		line-height:normal;
		text-align:left;
		font-weight:normal;
	}
	
	#subjectNameList{
		line-height:20px;
	}
	
	
	@media print{
		pageBreak{
			page-break-after:always;
			page-break-inside:avoid;
		}
	}
</style>

<html>
	<head>
		<title> Dokani: It Lab Solutions </title>
		<link rel="stylesheet" href="<?php echo base_url(); ?>style/transcript_style.css" type="text/css"/> 
		<!--script src="<?php echo base_url();?>assets/js/jquery.min.js"></script-->
	</head>
	
	<body>
		<div id="main">
			<div id="controller">
				<htmlpageheader name="myheader">
					<div id="header">
						<img style="width:10%;" class="schoolLogoHeaderSmall" src="<?php echo base_url();?>images/top_logo.png"/>
						<h1 style="font-size:18px; line-height:normal;width:90%;" class="schoolNameHeaderSmall"> 
							<?php echo $this->tank_auth->get_shopname().' ( '. $this->tank_auth->get_shopaddress().' ) '; ?>
						</h1>
						<h3 class="pageTitleSmall" style="margin:10px 0px 5px 0px;"> Purchase Return Report </h3>
					</div>
				</htmlpageheader>
				<htmlpagefooter name="myfooter">
					<div id="printFooter">
						<div class="part70P"> 
							<div class="developPart">
								<img class="companyLogo" src="<?php echo base_url();?>images/itlablogo.png" alt="IT Lab Solutions Ltd."/>
								
								<p> 
									Generated By : <b>Dokani</b> 
									<br/>
									Developed By : <b>IT Lab Solutions Ltd.</b> +8801842485222, www.itlabsolutions.com
								</p> 
							</div>
						</div>
						
						
						<div class="part30P">
							<div class="orgNameBottom textAlginRight">
								<p> <b>&copy; Copyright </b> <br/>  <?php echo $this->tank_auth->get_shopname();?>  </p>
								<p> <?php echo $this->tank_auth->get_shopaddress();?> </p>
							</div>
						</div>
					</div>
				</htmlpagefooter>
				<sethtmlpageheader name="myheader" value="on" show-this-page="1" />
				<sethtmlpagefooter name="myfooter" value="on" />

				<div class="row">
					<table class="simpleTable" style="margin-top:30px;">
						<thead>
							<tr class="tableRowBG">
								<th style="text-align:center;">No</th>
								<th style="text-align:center;">Date</th>
								<th style="text-align:center;">Distributor Name</th>
								<th style="text-align:center;">Product Name</th>
								<th style="text-align:center;">Quantity</th>
								<th style="text-align:center;">Buy Price</th>
							</tr>
						</thead>	
						<tbody>	
						<?php
							$i=1;
							$ii=1;
							$total_quantity =0;
							$total_price =0;
							foreach($return_main_product->result() as $tmp)
							{
						?>
							<tr>
								<th><?php echo $i;?></th>
								<th><?php echo $tmp->doc;?></th>
								<th><?php echo $tmp->distributor_name;?></th>
								<th><b>Main Product:</b> <?php echo $tmp->product_name;?><br>
									<?php
									
									foreach($return_warranty_product[$ii]->result() as $new_tmp)
									{
										echo '<b>Warranty Product:</b> '.$new_tmp->sl_no.'<br>';

									}
									?>
								</th>
								<th style="text-align:center;"><?php echo $tmp->return_quantity;?></th>
								<th style="text-align:center;"><?php echo $tmp->buy_price;?></th>
								
							</tr>
						<?php
							$total_quantity+=$tmp->return_quantity;
							$total_price+=$tmp->return_quantity*$tmp->buy_price;
							$ii++;
							$i++;
						}
						?>
						</tbody>
					</table>	
				</div>
				
				<div class="row">
					<h3 class="pageTitleSmall" style="margin:20px 0 5px 0;"> Summary </h3>
					<table class="simpleTable">
						<thead>
							<tr class="tableRowBG">
								<th colspan="3" style="text-align:center;">Total Quantity</th>
								<th colspan="3" style="text-align:center;">Total Price</th>
							</tr>
						</thead>	
						<tbody>	
							<tr>
								<th colspan="3" style="text-align:center;"> <?php echo $total_quantity; ?>  </th>
								<th colspan="3" style="text-align:center;"> <?php echo sprintf('%0.2f',$total_price); ?>  </th>
							</tr>
						</tbody>
					</table>
				</div>
			</div> <!---------- END OF DIV CONTROLLER ---------->
		</div>	<!--------- END OF DIV MAIN --------->
	</body>
</html>
