<?php 
	ini_set('memory_limit', '-1');
	//ini_set('MAX_EXECUTION_TIME', '-1');
	ini_set('max_execution_time', 300);
?>
<html>
	<head>
		<title> Dokani: It Lab Solutions </title>
		<link rel="stylesheet" href="<?php echo base_url(); ?>style/transcript_style.css" type="text/css"/> 
		<!--script src="<?php echo base_url();?>assets/js/jquery.min.js"></script-->
	</head>
	<style>
		.simpleTable{
			text-align:left;
		}
		
		.simpleTable th, .simpleTable td{
			line-height:normal;
			text-align:left;
			font-weight:normal;
		}
		
		#subjectNameList{
			line-height:20px;
		}
		
		
		@media print{
			pageBreak{
				page-break-after:always;
				page-break-inside:avoid;
			}
		}
	</style>
	<body>
		<div id="main">
			<div id="controller">
				<htmlpageheader name="myheader">
					<div id="header">
						<img style="width:10%;" class="schoolLogoHeaderSmall" src="<?php echo base_url();?>images/top_logo.png"/>
						<h1 style="font-size:18px; line-height:normal;width:90%;" class="schoolNameHeaderSmall"> 
							<?php echo $this->tank_auth->get_shopname().' ( '. $this->tank_auth->get_shopaddress().' ) '; ?>
						</h1>
						<h3 class="pageTitleSmall" style="margin:10px 0px 5px 0px;"> Stock Report </h3>
					</div>
				</htmlpageheader>

				<htmlpagefooter name="myfooter">
					<div id="printFooter">
						<div class="part70P"> 
							<div class="developPart">
								<img class="companyLogo" src="<?php echo base_url();?>images/itlablogo.png" alt="IT Lab Solutions Ltd."/>
								
								<p> 
									Generated By : <b>Dokani</b> 
									<br/>
									Developed By : <b>IT Lab Solutions Ltd.</b> +8801842485222, www.itlabsolutions.com
								</p> 
							</div>
						</div>
						
						
						<div class="part30P">
							<div class="orgNameBottom textAlginRight">
								<p> <b>&copy; Copyright </b> <br/>  <?php echo $this->tank_auth->get_shopname();?>  </p>
								<p> <?php echo $this->tank_auth->get_shopaddress();?> </p>
							</div>
						</div>
					</div>
				</htmlpagefooter>

				<sethtmlpageheader name="myheader" value="on" show-this-page="1" />
				<sethtmlpagefooter name="myfooter" value="on" />
				<div class="row">
					<table class="simpleTable" style="margin-top:15px;">
						<thead>
							<tr class="tableRowBG">
								<th colspan="3" style="text-align:center;">No</th>
								<th colspan="3" style="text-align:center;">ID</th>
								<th colspan="3" style="text-align:center;">Product</th>
								<th colspan="3" style="text-align:center;">Barcode</th>
								<th colspan="3" style="text-align:center;">Company</th>
								<th colspan="3" style="text-align:center;">Category</th>
								<th colspan="3" style="text-align:center;">Stock</th>
								<th colspan="3" style="text-align:center;">BP</th>
								<th colspan="3" style="text-align:center;">SP</th>
								<th colspan="3" style="text-align:center;">EP</th>
							</tr>
						</thead>	
						<tbody>	
						<?php
						$index = 1;
						$total_buy=0;
						$profit=0;
						$profit_percent=0;
						$total_profit=0;
						$final_profit_percent=0;
						$total_sale=0;
						$total_quantity=0;
						$total_sale_price=0;
						$total_buy_price=0;
						$total_shop_price=0;
						$grand2=0;
						$grand=0;
						foreach($down_data_stock -> result() as $field):
						?>
							<tr>
								<th colspan="3" style="text-align:center;"> <?php echo $index; ?>  </th>
								<th colspan="3" style="text-align:center;"> <?php echo $field->product_id; ?>  </th>
								<th colspan="3" style="text-align:left;"> <?php echo $field->product_name; ?>  </th>
								<th colspan="3" style="text-align:left;"> <?php echo $field->barcode; ?> </th>
								<th colspan="3" style="text-align:left;"> <?php echo $field->company_name; ?> </th>
								<th colspan="3" style="text-align:left;"> <?php echo $field->catagory_name; ?> </th>
								<th colspan="3" style="text-align:center;"> <?php echo $field -> stock_amount; ?> </th>
								<th colspan="3" style="text-align:right;"> <?php echo sprintf("%.2f",$field -> bulk_unit_buy_price); ?> </th>
								<th colspan="3" style="text-align:right;"> <?php echo sprintf("%.2f",$field -> bulk_unit_sale_price); ?> </th>
								<th colspan="3" style="text-align:right;"> <?php echo sprintf("%.2f",$field -> general_unit_sale_price); ?> </th>
								<?php 
										$total_buy_price += sprintf("%.2f",$field->bulk_unit_buy_price * $field->stock_amount);
										$total_sale_price += sprintf("%.2f",$field->bulk_unit_sale_price * $field->stock_amount);
										$total_shop_price += sprintf("%.2f",$field->general_unit_sale_price * $field->stock_amount);
										$total_quantity += $field -> stock_amount;
								?>
							</tr>
						<?php
							$index++;
							endforeach;
						?>
						</tbody>
					</table>	
				</div>
				
				<div class="row">
					<h3 class="pageTitleSmall" style="margin:20px 0 5px 0;"> Summary </h3>
					<table class="simpleTable">
						<thead>
							<tr class="tableRowBG">
								<th colspan="3" style="text-align:center;">Total Quantity</th>
								<th colspan="3" style="text-align:center;">Total Buy Price</th>
								<th colspan="3" style="text-align:center;">Total Sale Price</th>
								<th colspan="3" style="text-align:center;">Total Shop Price</th>
							</tr>
						</thead>	
						<tbody>	
							<tr>
								<th colspan="3" style="text-align:center;"> <?php echo $total_quantity; ?>  </th>
								<th colspan="3" style="text-align:center;"> <?php echo sprintf("%.2f",$total_buy_price); ?>  </th>
								<th colspan="3" style="text-align:center;"> <?php echo sprintf("%.2f",$total_sale_price); ?>  </th>
								<th colspan="3" style="text-align:center;"> <?php echo sprintf("%.2f",$total_shop_price); ?>  </th>
							</tr>
						</tbody>
					</table>
				</div>
			</div> <!---------- END OF DIV CONTROLLER ---------->
		</div>	<!--------- END OF DIV MAIN --------->
	</body>
</html>
