<?php 
	ini_set('memory_limit', '-1');
	//ini_set('MAX_EXECUTION_TIME', '-1');
	ini_set('max_execution_time', 300);
?>
<style>
	.simpleTable{
		text-align:left;
	}
	
	.simpleTable th, .simpleTable td{
		line-height:normal;
		text-align:left;
		font-weight:normal;
	}
	
	#subjectNameList{
		line-height:20px;
	}
	
	
	@media print{
		pageBreak{
			page-break-after:always;
			page-break-inside:avoid;
		}
	}
</style>

<html>
	<head>
		<title> Dokani: It Lab Solutions </title>
		<link rel="stylesheet" href="<?php echo base_url(); ?>style/transcript_style.css" type="text/css"/> 
		<!--script src="<?php echo base_url();?>assets/js/jquery.min.js"></script-->
	</head>
	
	<body>
		<div id="main">
			<div id="controller">
				<htmlpageheader name="myheader">
					<div id="header">
						<img style="width:10%;" class="schoolLogoHeaderSmall" src="<?php echo base_url();?>images/top_logo.png"/>
						<h1 style="font-size:18px; line-height:normal;width:90%;" class="schoolNameHeaderSmall"> 
							<?php echo $this->tank_auth->get_shopname().' ( '. $this->tank_auth->get_shopaddress().' ) '; ?>
						</h1>
						<h3 class="pageTitleSmall" style="margin:10px 0px 5px 0px;"> SCB Report </h3>
					</div>
				</htmlpageheader>
				<htmlpagefooter name="myfooter">
					<div id="printFooter">
						<div class="part70P"> 
							<div class="developPart">
								<img class="companyLogo" src="<?php echo base_url();?>images/itlablogo.png" alt="IT Lab Solutions Ltd."/>
								
								<p> 
									Generated By : <b>Dokani</b> 
									<br/>
									Developed By : <b>IT Lab Solutions Ltd.</b> +8801842485222, www.itlabsolutions.com
								</p> 
							</div>
						</div>
						
						
						<div class="part30P">
							<div class="orgNameBottom textAlginRight">
								<p> <b>&copy; Copyright </b> <br/>  <?php echo $this->tank_auth->get_shopname();?>  </p>
								<p> <?php echo $this->tank_auth->get_shopaddress();?> </p>
							</div>
						</div>
					</div>
				</htmlpagefooter>
				<sethtmlpageheader name="myheader" value="on" show-this-page="1" />
				<sethtmlpagefooter name="myfooter" value="on" />
				<div class="row">
					<div style="width:30%;float:left;">
						<div class="box-header with-border" style="background: #bbbfc1;width:98%;">
							<center><h3 class="box-title" style="text-align:center;font-family:Helvetica Neue,Helvetica,Arial,sans-serif;font-weight:normal;">Stock Report</h3></center>
							<h5 style="text-align:center;"> 
							<?php
								$start_date = $this->uri->segment(3);
								$end_date = $this->uri->segment(4);
								if(($start_date!=''&& $end_date=='null'))
								{
									$start_date = $start_date;
									$end_date = $start_date;
								}
								else if($start_date=='' && $end_date=='')
								{
									$start_date = $bd_date;
									$end_date = $bd_date;
								}
								else
								{
									$start_date = $start_date;
									$end_date = $end_date;
								}
							?>
							Date Range : <?php echo $start_date.'--'.$end_date;?>
						  </h5>
						</div>
						<table class="simpleTable" style="width:98%;">
							<thead>
								<tr class="tableRowBG">
									<th colspan="3">Title</th>
									<th colspan="3" style="text-align:right;">Amount</th>
								</tr>
							</thead>	
							<tbody>	
								<tr>
									<th colspan="3"> Opening Stock (+) </th>
									<th colspan="3" style="text-align:right;"><?php echo sprintf('%0.2f',$opening_stock);?></th>
								</tr>
								<tr>
									<?php
					$purchase_total_amount = 0;
					foreach($payable_receivable_financial_statement['updated_purchase'] -> result() as $field):	
						 $temp_payable_1 = $field -> unpaid_grand_total - $field -> total_paid_amount;
						 $purchase_total_amount = $field -> total_purchase_amount;
					endforeach;
				?>
									<th colspan="3"> Purchase (+) </th>
									<th colspan="3" style="text-align:right;"><?php echo sprintf('%0.2f',$purchase_total_amount); ?></th>
								</tr>
								<tr>
									<th colspan="3"> Purchase Return (-)</th>
									<th colspan="3" style="text-align:right;"><?php echo sprintf('%0.2f',$purchase_return_info); ?></th>
								</tr>
								<tr>
									<th colspan="3"> Sale (-)</th>
									<th colspan="3" style="text-align:right;"><?php echo sprintf('%0.2f',$sale_price_info);?></th>
								</tr>
								<tr>
									<th colspan="3"> Sale Return (+)</th>
									<th colspan="3" style="text-align:right;"><?php echo sprintf('%0.2f',$sale_return_info);?></th>
								</tr>
								<tr>
									<th colspan="3"> Closing Stock</th>
									<th colspan="3" style="text-align:right;"><?php echo sprintf('%0.2f',$opening_stock+$purchase_total_amount-$purchase_return_info-$sale_price_info+$sale_return_info);?></th>
								</tr>
							</tbody>
						</table>
					</div>
					<div style="width:35%;float:left;">
						<div class="box-header with-border" style="background: #bbbfc1;width:98%;">
							<center><h3 class="box-title" style="text-align:center;font-family:Helvetica Neue,Helvetica,Arial,sans-serif;font-weight:noraml;">Cash Book</h3></center>
							<h5 style="text-align:center;">
							  <?php
								$start_date = $this->uri->segment(3);
								$end_date = $this->uri->segment(4);
								if(($start_date!=''&& $end_date=='null'))
								{
									$start_date = $start_date;
									$end_date = $start_date;
								}
								else if($start_date=='' && $end_date=='')
								{
									$start_date = $bd_date;
									$end_date = $bd_date;
								}
								else
								{
									$start_date = $start_date;
									$end_date = $end_date;
								}
							  ?>
							  Date Range : <?php echo $start_date.'--'.$end_date;?>
							  </h5>
							
						</div>
						<table class="simpleTable" style="width:98%;">
							<thead>
								<tr class="tableRowBG">
									<th colspan="3">Title</th>
									<th colspan="3" style="text-align:right;">Amount</th>
								</tr>
							</thead>	
							<tbody>	
								<tr>
									<th colspan="3"> Opening Balance (+)</th>
									<th colspan="3" style="text-align:right;">
										<?php 
											$in = $from_bank_opening+$from_owner_opening+$cash_sale_opening+$cash_delivery_charge_opening+$cash_credit_collection_opening;
											$out = $to_bank_opening+$to_owner_opening+$cash_sale_return_opening+$cash_purchase_payment_opening+$cash_expense_payment_opening;
											$opening_balance = $in-$out;
											echo sprintf('%0.2f',$opening_balance);
										?>
									</th>
								</tr>
								<tr>
									<th colspan="3">From Bank (+)</th>
									<th colspan="3" style="text-align:right;"><?php echo sprintf('%0.2f',$from_bank); ?></th>
								</tr>
								<tr>
									<th colspan="3">To Bank (-)</th>
									<th colspan="3" style="text-align:right;"><?php echo sprintf('%0.2f',$to_bank); ?></th>
								</tr>
								<tr>
									<th colspan="3">From Owner (+)</th>
									<th colspan="3" style="text-align:right;"><?php echo sprintf('%0.2f',$from_owner);?></th>
								</tr>
								<tr>
									<th colspan="3">To Owner (-)</th>
									<th colspan="3" style="text-align:right;"><?php echo sprintf('%0.2f',$to_owner);?></th>
								</tr>
								<tr>
									<th colspan="3">Cash Sale (+)</th>
									<th colspan="3" style="text-align:right;"><?php echo sprintf('%0.2f',$cash_sale);?></th>
								</tr>
								<tr>
									<th colspan="3">Delivery Charge (+)</th>
									<th colspan="3" style="text-align:right;"><?php echo sprintf('%0.2f',$cash_delivery_charge);?></th>
								</tr>
								<tr>
									<th colspan="3">Due Collection (+)</th>
									<th colspan="3" style="text-align:right;"><?php echo sprintf('%0.2f',$cash_credit_collection);?></th>
								</tr>
								<tr>
									<th colspan="3">Cash Sale Return (-)</th>
									<th colspan="3" style="text-align:right;"><?php echo sprintf('%0.2f',$cash_sale_return);?></th>
								</tr>
								<tr>
									<th colspan="3">Purchase Payment (-)</th>
									<th colspan="3" style="text-align:right;"><?php echo sprintf('%0.2f',$cash_purchase_payment);?></th>
								</tr>
								<tr>
									<th colspan="3">Purchase Cash Return (+)</th>
									<th colspan="3" style="text-align:right;">0.00</th>
								</tr>
								<tr>
									<th colspan="3">Expense Payment (-)</th>
									<th colspan="3" style="text-align:right;"><?php echo sprintf('%0.2f',$cash_expense_payment);?></th>
								</tr>
								<tr>
									<th colspan="3">Cash in Hand</th>
									<th colspan="3" style="text-align:right;">
										<?php 
											$in = $opening_balance+$from_bank+$from_owner+$cash_sale+$cash_delivery_charge+$cash_credit_collection;
											$out = $to_bank+$to_owner+$cash_sale_return+$cash_purchase_payment+$cash_expense_payment;
										
											echo sprintf('%0.2f',$in-$out);
										?>
									</th>
								</tr>
							</tbody>
						</table>
					</div>
					<div style="width:35%;float:right;">
						<div class="box-header with-border" style="background: #bbbfc1;width:100%;">
							<center><h3 class="box-title" style="text-align:center;font-family:Helvetica Neue,Helvetica,Arial,sans-serif;font-weight:noraml;">Bank Book</h3></center>
							
							<h5 style="text-align:center;">
							  <?php
								$start_date = $this->uri->segment(3);
								$end_date = $this->uri->segment(4);
								if(($start_date!=''&& $end_date=='null'))
								{
									$start_date = $start_date;
									$end_date = $start_date;
								}
								else if($start_date=='' && $end_date=='')
								{
									$start_date = $bd_date;
									$end_date = $bd_date;
								}
								else
								{
									$start_date = $start_date;
									$end_date = $end_date;
								}
							  ?>
							  Date Range : <?php echo $start_date.'--'.$end_date;?>
							  </h5>
						</div>
						<table class="simpleTable" style="width:100%;">
							<thead>
								<tr class="tableRowBG">
									<th colspan="3">Title</th>
									<th colspan="3" style="text-align:right;">Amount</th>
								</tr>
							</thead>	
							<tbody>	
								<tr>
									<th colspan="3"> Opening Balance (+)</th>
									<th colspan="3" style="text-align:right;">
										<?php 
											$in = $from_bank_opening+$from_owner_opening+$cash_sale_opening+$cash_delivery_charge_opening+$cash_credit_collection_opening;
											$out = $to_bank_opening+$to_owner_opening+$cash_sale_return_opening+$cash_purchase_payment_opening+$cash_expense_payment_opening;
											$opening_balance = $in-$out;
											echo sprintf('%0.2f',$opening_balance);
										?>
									</th>
								</tr>
								<tr>
									<th colspan="3">From Bank (+)</th>
									<th colspan="3" style="text-align:right;"><?php echo sprintf('%0.2f',$from_bank); ?></th>
								</tr>
								<tr>
									<th colspan="3">To Bank (-)</th>
									<th colspan="3" style="text-align:right;"><?php echo sprintf('%0.2f',$to_bank); ?></th>
								</tr>
								<tr>
									<th colspan="3">From Owner (+)</th>
									<th colspan="3" style="text-align:right;"><?php echo sprintf('%0.2f',$from_owner);?></th>
								</tr>
								<tr>
									<th colspan="3">To Owner (-)</th>
									<th colspan="3" style="text-align:right;"><?php echo sprintf('%0.2f',$to_owner);?></th>
								</tr>
								<tr>
									<th colspan="3">Card Sale (+)</th>
									<th colspan="3" style="text-align:right;"><?php echo sprintf('%0.2f',$cash_sale);?></th>
								</tr>
								<tr>
									<th colspan="3">Delivery Charge (+)</th>
									<th colspan="3" style="text-align:right;"><?php echo sprintf('%0.2f',$cash_delivery_charge);?></th>
								</tr>
								<tr>
									<th colspan="3">Due Collection (+)</th>
									<th colspan="3" style="text-align:right;"><?php echo sprintf('%0.2f',$cash_credit_collection);?></th>
								</tr>
								<tr>
									<th colspan="3">Bank Sale Return (-)</th>
									<th colspan="3" style="text-align:right;"><?php echo sprintf('%0.2f',$cash_sale_return);?></th>
								</tr>
								<tr>
									<th colspan="3">Purchase Payment (-)</th>
									<th colspan="3" style="text-align:right;"><?php echo sprintf('%0.2f',$cash_purchase_payment);?></th>
								</tr>
								<tr>
									<th colspan="3">Purchase Bank Return (+)</th>
									<th colspan="3" style="text-align:right;">0.00</th>
								</tr>
								<tr>
									<th colspan="3">Expense Payment (-)</th>
									<th colspan="3" style="text-align:right;"><?php echo sprintf('%0.2f',$cash_expense_payment);?></th>
								</tr>
								<tr>
									<th colspan="3">Cash in Bank</th>
									<th colspan="3" style="text-align:right;">
										<?php 
											$in = $opening_balance+$from_bank+$from_owner+$cash_sale+$cash_delivery_charge+$cash_credit_collection;
											$out = $to_bank+$to_owner+$cash_sale_return+$cash_purchase_payment+$cash_expense_payment;
										
											echo sprintf('%0.2f',$in-$out);
										?>
									</th>
								</tr>
							</tbody>
						</table>
					</div>
				</div>
			</div> <!---------- END OF DIV CONTROLLER ---------->
		</div>	<!--------- END OF DIV MAIN --------->
	</body>
</html>
