<?php 
	ini_set('memory_limit', '-1');
	//ini_set('MAX_EXECUTION_TIME', '-1');
	ini_set('max_execution_time', 300);
?>
<style>
	.simpleTable{
		text-align:left;
	}
	
	.simpleTable th, .simpleTable td{
		line-height:normal;
		text-align:left;
		font-weight:normal;
	}
	
	#subjectNameList{
		line-height:20px;
	}
	
	
	@media print{
		pageBreak{
			page-break-after:always;
			page-break-inside:avoid;
		}
	}
</style>

<html>
	<head>
		<title> Dokani: It Lab Solutions </title>
		<link rel="stylesheet" href="<?php echo base_url(); ?>style/transcript_style.css" type="text/css"/> 
		<!--script src="<?php echo base_url();?>assets/js/jquery.min.js"></script-->
	</head>
	
	<body>
		<div id="main">
			<div id="controller">
				<htmlpageheader name="myheader">
					<div id="header">
						<img style="width:10%;" class="schoolLogoHeaderSmall" src="<?php echo base_url();?>images/top_logo.png"/>
						<h1 style="font-size:18px; line-height:normal;width:90%;" class="schoolNameHeaderSmall"> 
							<?php echo $this->tank_auth->get_shopname().' ( '. $this->tank_auth->get_shopaddress().' ) '; ?>
						</h1>
						<h3 class="pageTitleSmall" style="margin:10px 0px 5px 0px;"> Purchase Report </h3>
					</div>
				</htmlpageheader>
				<htmlpagefooter name="myfooter">
					<div id="printFooter">
						<div class="part70P"> 
							<div class="developPart">
								<img class="companyLogo" src="<?php echo base_url();?>images/itlablogo.png" alt="IT Lab Solutions Ltd."/>
								
								<p> 
									Generated By : <b>Dokani</b> 
									<br/>
									Developed By : <b>IT Lab Solutions Ltd.</b> +8801842485222, www.itlabsolutions.com
								</p> 
							</div>
						</div>
						
						
						<div class="part30P">
							<div class="orgNameBottom textAlginRight">
								<p> <b>&copy; Copyright </b> <br/>  <?php echo $this->tank_auth->get_shopname();?>  </p>
								<p> <?php echo $this->tank_auth->get_shopaddress();?> </p>
							</div>
						</div>
					</div>
				</htmlpagefooter>
				<sethtmlpageheader name="myheader" value="on" show-this-page="1" />
				<sethtmlpagefooter name="myfooter" value="on" />

				<div class="row">
					<table class="simpleTable" style="margin-top:15px;">
						<thead>
							<tr class="tableRowBG">
								<th colspan="3" style="text-align:center;">No</th>
								<th colspan="3" style="text-align:center;">Date</th>
								<th colspan="3" style="text-align:center;">Receipt</th>
								<th colspan="6" style="text-align:center;">Distributor</th>
								<th colspan="6" style="text-align:center;">Company</th>
								<th colspan="6" style="text-align:center;">Category</th>
								<th colspan="6" style="text-align:center;">Product</th>
								<th colspan="6" style="text-align:center;">Quantity</th>
								<th colspan="6" style="text-align:center;">BP</th>
								<th colspan="6" style="text-align:center;">SP</th>
								<th colspan="6" style="text-align:center;">Price</th>
							</tr>
						</thead>	
						<tbody>	
						<?php
						$index = 1;
						$total_buy=0;
						$total_quantity=0;
						$total_damage=0;
						$final_damage=0;
						$gran_tot=0;
						foreach($download_data_purchase -> result() as $field):
						?>
							<tr>
								<th colspan="3" style="text-align:center;"> <?php echo $index; ?>  </th>
								<th colspan="3" style="text-align:center;"> <?php echo $field->receipt_date; ?>  </th>
								<th colspan="3" style="text-align:center;"> <?php echo $field->receipt_id; ?>  </th>
								<th colspan="6" style="text-align:center;"> <?php echo $field->distributor_name; ?>  </th>
								<th colspan="6" style="text-align:center;"> <?php echo $field->company_name; ?> </th>
								<th colspan="6" style="text-align:center;"> <?php echo $field->catagory_name; ?> </th>
								<th colspan="6" style="text-align:center;"> <?php echo $field->product_name; ?> </th>
								<th colspan="6" style="text-align:center;"> <?php echo $field -> purchase_quantity; ?> </th>
								<td colspan="6" style="text-align:right;"> <?php $u_bp = $field ->unit_buy_price; echo sprintf("%.2f",$u_bp); ?> </td>
								<td colspan="6" style="text-align:right;"> <?php $u_sp= $field ->bulk_unit_sale_price; echo sprintf("%.2f",$u_sp); ?> </td>
								<td colspan="6" style="text-align:right;"> <?php echo sprintf("%.2f",$field -> purchase_quantity * $field ->unit_buy_price); ?> </td>
								
								
								<?php $gran_tot = $field -> grand_total;?>
								<?php $total_quantity += $field -> purchase_quantity;?>
								<?php $grand = ($field -> purchase_quantity * $field ->unit_buy_price);?>
								<?php $total_buy += $grand;?>
							</tr>
						<?php
							$index++;
							endforeach;
							
						?>
						</tbody>
					</table>
				</div>
				
				<div class="row">
					<h3 class="pageTitleSmall" style="margin:20px 0 5px 0;"> Summary </h3>
					<table class="simpleTable" style="margin-top:30px;">
						<thead>
							<tr class="tableRowBG">
								<?php if($this->uri->segment(3)!='' && $this->uri->segment(3)!='null'){?>
								<th colspan="3" style="text-align:right;">Receipt Total</th>
								<?php } ?>
								<th colspan="3" style="text-align:right;">Purchase Quantity</th>
								<th colspan="3" style="text-align:right;">Total Price</th>
							</tr>
						</thead>	
						<tbody>	
							<tr>
								<?php if($this->uri->segment(3)!='' && $this->uri->segment(3)!='null'){?>
								<th colspan="3" style="text-align:right;"> <?php echo sprintf("%.2f",$gran_tot); ?>  </th>
								<?php } ?>
								<th colspan="3" style="text-align:right;"> <?php echo $total_quantity; ?>  </th>
								<th colspan="3" style="text-align:right;"> <?php echo sprintf("%.2f",$total_buy); ?>  </th>
							</tr>
						</tbody>
					</table>
				</div>
			</div> <!---------- END OF DIV CONTROLLER ---------->
		</div>	<!--------- END OF DIV MAIN --------->
	</body>
</html>
